name: Flobby
description: $description
version: '${version}'

main: me.lukiiy.flobby.Flobby
api-version: '1.21.8'
load: POSTWORLD

authors: [ Lukiiy ]

dependencies:
  server:
    Flow:
      load: BEFORE
      required: true
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true